# JARVIS Unified Configuration
jarvis:
  name: "JARVIS"
  version: "1.0.0"
  mode: "development"  # development, testing, production
  
  # AI Configuration
  ai:
    enabled: true
    primary: "claude"  # claude, openai, local
    fallback_enabled: true
    
    claude:
      enabled: true
      api_key: ${CLAUDE_API_KEY}
      model: "claude-3-opus-20240229"
      max_tokens: 4000
      
    openai:
      enabled: true
      api_key: ${OPENAI_API_KEY}
      model: "gpt-4-turbo-preview"
      max_tokens: 4000
      
  # Features (start disabled, enable gradually)
  features:
    consciousness: false
    self_healing: false
    neural_resource: false
    quantum_optimization: false
    emotional_intelligence: false
    
  # System Settings
  system:
    max_memory_mb: 4096
    max_cpu_percent: 80
    log_level: "INFO"
    
  # Database
  database:
    type: "sqlite"
    path: "jarvis.db"
