#!/bin/bash
# Claude Memory RAG - Useful Commands

echo "🧠 Claude Memory RAG - Quick Reference"
echo "===================================="
echo ""
echo "📋 VERIFICATION & TESTING:"
echo "  python3 verify_setup.py         # Check if everything is set up"
echo "  python3 test_memory_functions.py # Test memory functionality"
echo "  python3 reset_memory.py         # Clear all memory data"
echo ""
echo "🔧 MANUAL SERVER TESTING:"
echo "  # Initialize test:"
echo "  echo '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}' | python3 server_simple_working.py"
echo ""
echo "  # List tools test:"
echo "  echo '{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\",\"params\":{}}' | python3 server_simple_working.py"
echo ""
echo "📁 IMPORTANT LOCATIONS:"
echo "  Server: $(pwd)/server_simple_working.py"
echo "  Memory: ~/.claude_simple_memory/memory.json"
echo "  Config: ~/Library/Application Support/Claude/claude_desktop_config.json"
echo ""
echo "🚀 USAGE IN CLAUDE:"
echo "  1. Restart Claude Desktop"
echo "  2. Use the 'claude-memory' MCP tools:"
echo "     - store_conversation"
echo "     - recall_memories"
echo "     - get_memory_stats"
echo "     - learn_pattern"
echo ""
echo "💡 TROUBLESHOOTING:"
echo "  - If server fails: Check 'Open Logs Folder' in Claude"
echo "  - If no tools appear: Restart Claude Desktop"
echo "  - If dependencies missing: pip install numpy"
echo ""
